---
logging:
  level: INFO
  loggers:
    task: DEBUG
database:
  driverClass: org.mariadb.jdbc.Driver
  user: root
  password: Emperor
  url: jdbc:mariadb://localhost:3306/taskDB
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate.hbm2ddl.auto: update
    hibernate.show_sql: true
