version: '3.9'

services:
  mariadb:
    image: mariadb
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build:
      context: .
    container_name: dropwizard_app_container
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mariadb://mariadb_container:3306/${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/app/config.yml:ro


volumes:
  mariadb_data:
